blank_issues_enabled: true
contact_links:
  - name: 💬 Support
    url: https://eventalerts.gg/development
    about: "If you need help with the mod or have a question please join the Development Discord server and ask there"
