blank_issues_enabled: true
contact_links:
  - name: 💬 Support
    url: https://eventalerts.gg/development?utm_source=github&utm_medium=issue_template&utm_campaign=support
    about: "If you need help with the mod or have a question please join the Development Discord server and ask there"
